name: darts
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: Darts
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - darts
      - hspec
